app/routes/admin.py
from app import app, db, login_manager
from ..models.users import User
from flask import Blueprint, render_template
from flask_login import current_user, login_required

admin = Blueprint(
    "admin", __name__, template_folder="../templates/admin",
    url_prefix="/admin"
)


@login_required
@admin.route("/users")
def view_all_users():
    if current_user.is_admin():
        return render_template("users.html", page_title="All users")

app/routes/auth.py
from app import app, db, login_manager
from app.models.users import User
from flask import Blueprint
from flask import render_template, request, redirect, flash, url_for
from werkzeug.urls import url_parse
from app.forms.login import LoginForm, RegistrationForm, flash_form_errors
from flask_login import current_user, login_user, login_required, logout_user


auth = Blueprint("auth", __name__, template_folder="../templates/auth/")


@login_required
@auth.route("/login", methods=["POST", "GET"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('index'))
    login_form = LoginForm(request.form)
    if login_form.validate_on_submit():
        user = User.query.filter_by(email=request.form["email"]).first()
        if user is None or not user.check_password(request.form["password"]):
            flash("Invalid username or password")
            return redirect(url_for("auth.login"))
        remember_me = False
        if "remember_me" in request.form:
            remember_me = True
        login_user(user, remember=remember_me)
        next_page = request.args.get("next")
        if not next_page or url_parse(next_page).netloc != "":
            next_page = url_for("index")
        return redirect(next_page)
    flash_form_errors(login_form)
    return render_template(
        "login.html",
        page_title="Log in",
        form=login_form
    )


@auth.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("index"))


@auth.route("/register", methods=["POST", "GET"])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('index'))
    form = RegistrationForm(request.form)
    if form.validate_on_submit():
        user = User.create_user(
            first_name=request.form["first_name"],
            last_name=request.form["last_name"],
            email=request.form["email"],
            password=request.form["password"]

        )
        if user is not None:
            flash("Successfully registered.")
            return redirect(url_for("index"))
        else:
            flash("Error registering user. Please try again")
            return redirect(url_for("index"))
    flash_form_errors(form)
    return render_template("register.html", form=form, page_title="Register")


login_manager.login_view = "auth.login"

app/templates/partials/navbar.html
<nav class="w-full z-50 flex items-center justify-between flex-wrap bg-white py-4 px-6 border-b border-gray-400fixed">
    <div class="flex items-center flex-shrink-0 text-gray-700 mr-6">
        <a href="/">
            <span class="font-semibold text-xl tracking-tight">ML.ai</span>
        </a>
    </div>
    <div class="block md:hidden lg:hidden">
        <button class="flex items-center px-3 py-2 border rounded bg-gray-500 text-gray-400 hover:text-white">
            <svg class="fill-current h-3 w-3" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><title>Menu</title><path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"/></svg>
        </button>
    </div>
    <div class="w-full block flex-grow md:flex md:items-center md:w-auto sm:hidden">
        <div class="text-md md:flex-grow text-right">
            {% if current_user.is_anonymous %}
            <a href="{{ url_for('auth.register') }}" class="block mt-4 md:inline-block md:mt-0 text-gray-600 hover:text-gray-500 ml-4">
                Register
            </a>
            <a href="{{ url_for('auth.login') }}" class="block mt-4 md:inline-block md:mt-0 text-gray-600 hover:text-gray-500 ml-4">
                Login
            </a>
            {% else %}
                {% if current_user.is_admin() %}
                <a href="{{ url_for('admin.view_all_users') }}" class="block mt-4 md:inline-block md:mt-0 text-gray-600 hover:text-gray-500 ml-4">
                    Users
                </a>
                {% endif %}
                <a href="{{ url_for('user_jobs') }}" class="block mt-4 md:inline-block md:mt-0 text-gray-600 hover:text-gray-500 ml-4">
                    Jobs
                </a>
                <a href="{{ url_for('auth.logout') }}" class="block mt-4 md:inline-block md:mt-0 text-gray-600 hover:text-gray-500 ml-4">
                    Logout
                </a>
                |
                Hi {{ current_user.first_name }}
            {% endif %}
        </div>
    </div>
</nav>